apiVersion: v1
kind: Service
metadata:
  name: spring-boot-dekorate-demo-service
spec:
  ports:
    - port: 3000
      targetPort: 8080
  selector:
    app: spring-boot-dekorate-demo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-dekorate-demo-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-dekorate-demo
  template:
    metadata:
      labels:
        app: spring-boot-dekorate-demo
    spec:
      containers:
        - env:
            - name: APP_GREETING
              value: from dev environment
          image: spring-boot-dekorate-demo:895a717f78178e7b89af276196b748e90cb238651bc0bf9ba6a7209e2aead4e1
          name: spring-boot-dekorate-demo
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 32Mi
