apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: spring-boot-dekorate-demo
build:
  artifacts:
    - image: spring-boot-dekorate-demo
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        env:
          - GOOGLE_RUNTIME_VERSION=17
manifests:
  kustomize:
    paths:
      - kustomization/overlays/dev


profiles:
  - name: acptProfile
    manifests:
      kustomize:
        paths:
          - kustomization/overlays/acpt

  - name: prodProfile
    manifests:
      kustomize:
        paths:
          - kustomization/overlays/prod
