apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-dekorate-demo-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-dekorate-demo
  template:
    metadata:
      labels:
        app: spring-boot-dekorate-demo
    spec:
      containers:
      - name: spring-boot-dekorate-demo
        image: spring-boot-dekorate-demo
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
