apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-dekorate-demo-deployment
spec:
  template:
    spec:
      containers:
        - name:  spring-boot-dekorate-demo
          image: ghcr.io/rmortale/spring-boot-dekorate-demo:2deec5fa
          env:
            - name: APP_GREETING
              value: from PROD environment