apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-dekorate-demo-deployment
spec:
  template:
    spec:
      containers:
        - name:  spring-boot-dekorate-demo
          image: ghcr.io/rmortale/spring-boot-dekorate-demo:develop
          env:
            - name: APP_GREETING
              value: from dev environment
            - name: JAVA_TOOL_OPTIONS
              value: -XX:MaxMetaspaceSize=64M -XX:ReservedCodeCacheSize=32M -Xss136K