name: build

on:
  push:
    paths-ignore:
      - 'kustomization/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test
        run: mvn -B clean test

      - name: Build and push
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            export IMAGE_TAG=${GITHUB_SHA::8}
          else
            export IMAGE_TAG=`echo $GITHUB_REF_NAME|sed 's#/#-#g'`
          fi
          mvn -B package -DskipTests com.google.cloud.tools:jib-maven-plugin:build \
            -Dimage=$REGISTRY/$IMAGE_NAME:$IMAGE_TAG
